; ── Shared base — inherited by all [env:xxx] sections ─────────
[env]
platform      = espressif32
framework     = arduino
extra_scripts =
    tools/embed_web.py
    tools/patch.py
    post:tools/build.py

lib_deps =
    m5stack/M5Unified
    ESP32Async/ESPAsyncWebServer
    ESP32Async/AsyncTCP

monitor_speed = 115200
upload_speed  = 921600

; ── M5Stack CoreS3 (320×240) ───────────────────────────────────
[env:m5stack-cores3]
board = m5stack-cores3
build_src_filter = +<*>
build_flags =
    -DARDUINO_M5STACK_CORES3
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
